import { IBM_Plex_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/ui/shared/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import AnimatedBackground from "@/components/ui/sections/animatedBacground/animated-background";
import ChatBot from "@/components/ui/sections/chatBot/chat-bot";
import PageLoader from "@/components/ui/shared/page-loader";

const IBM = IBM_Plex_Sans({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
  display: "swap", // prevents invisible text while loading
});

export const metadata = {
  title: "BumbleBee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html
        suppressHydrationWarning
        lang="en"
        className={`${IBM.className} antialiased`}
      >
        <body suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            forcedTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* Loader Overlay */}
            <PageLoader />

            {/* Animated Background */}
            <AnimatedBackground />

            {/* Content */}
            <div className="relative z-10">
              <Header />
              <main className="min-h-screen">
                {children}
                <ChatBot />
              </main>
              <footer className="py-12 border border-b relative">
                <div className="container px-4 mx-auto text-center text-black">
                  <p>2025 BumbleBee. All Rights Reserved</p>
                </div>
              </footer>
            </div>

            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
